export const SHOWCATEGORY = 'SHOWCATEGORY';
export const SHOWPRODUCT = 'SHOWPRODUCT'
export const SHOWCATPRODUCT = 'SHOWCATPRODUCT'
export const ADDTOCART = 'ADDTOCART'
export const SHOWCART = 'SHOWCART'
export const SETQTY = 'SETQTY'
export const DELETECART = 'DELETECART'
export const SHOWPRODUCTDISCOUNT = 'SHOWPRODUCTDISCOUNT'
export const DETAILPRODUCT = 'DETAILPRODUCT'













//call api
export const CALLAPI_LIST_CART = 'CALLAPI_LIST_CART'





